config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  resources :lists, param: :list_uuid, only: [:show] do
    member do
      delete :archive
    end
  end
  post '/lists/:list_uuid/items', to: 'items#create', as: 'list_items'

  namespace :api do
    resources :lists, param: :uuid, only: [:create] do
      resources :items, only: [:update]
    end
  end

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  checked    :boolean          default(FALSE), not null
#  list_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Item < ActiveRecord::Base
  belongs_to :list

  validates :title,     presence: true
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  list_uuid  :string(255)      not null
#  archived   :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_lists_on_list_uuid  (list_uuid) UNIQUE
#

class List < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items,
    reject_if: proc { |obj| obj['title'].blank? }

  validates :title,     presence: true
  validates :list_uuid, presence: true,
                        uniqueness: true

  before_validation :set_list_uuid

  private
    def set_list_uuid
      self.list_uuid = SecureRandom.uuid
    end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/items_controller.rb
class Api::ItemsController < Api::ApplicationController
  before_action :set_list, only: [:update]

  def update
    @item = @list.items.find(params[:id])
    checked = params[:checked] == 'true'
    @item.update_attribute :checked, checked
  end
end

app/controllers/api/lists_controller.rb
class Api::ListsController < Api::ApplicationController
  def create
    items = params[:items].to_s.split(',')
    @list = List.create(
      title: params[:title],
      items_attributes: items.map{ |item| {title: item} }
    )
    respond_to do |format|
      if @list.persisted?
        format.json { render }
      else
        format.json {
          render json: false.to_json, status: 400
        }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def set_list
      @list = List.where(archived: false).includes(:items).order('items.created_at asc').find_by(list_uuid: params[:list_uuid])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list, only: [:create]

  def create
    @item = @list.items.create item_params
    respond_to do |format|
      format.html {
        if @item.persisted?
          redirect_to list_url(@list.list_uuid), notice: 'An item was successfully created.'
        else
          redirect_to list_url(@list.list_uuid), alert: 'An item was not successfully created.'
        end
      }
    end
  end

  private
    def item_params
      params.require(:item).permit(:title)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :archive]

  def show
    @new_item = Item.new(list: @list)
  end

  def archive
    message = nil
    if @list
      @list.update_attribute :archived, true
      message = 'A list has been successfully archived.'
    end
    redirect_to root_path, notice: message
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Chcklst
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
  %body

    .container
      .row
        .col-lg-12
          = yield :h1
          - if notice
            .notice-block
              .alert.alert-info.alert-dismissable
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
                %i.fa.fa-info-circle
                = notice
          - if alert
            .alert-block
              .alert.alert-danger.alert-dismissable
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
                %i.fa.fa-info-circle
                = alert

      = yield

    = javascript_include_tag 'application'
    = yield :script

app/views/lists/show.html.haml
- if @list
  %h1= @list.title

  = form_tag archive_list_path(@list.list_uuid), method: :delete do
    - @list.items.each do |item|
      .checkbox
        %label
          = check_box_tag item.id, 'true', item.checked, { data: { 'update-url' => api_list_item_path(@list.list_uuid, item) } }
          = item.title
    = button_tag 'Delete this list', class: 'btn btn-danger', type: :submit, data: { confirm: 'Are you sure?' }

  %hr

  %h2 Need more items?
  .row
    .col-sm-3
      = form_for @new_item, url: list_items_path(list_uuid: @list.list_uuid) do |f|
        .form-group
          = f.text_field :title, class: 'form-control', placeholder: 'new item name'
        = f.button 'Add a new item', class: 'btn btn-primary', type: :submit

- else
  .alert.alert-danger{ role: :alert }
    %strong
      Oops!
    This list has been deleted already.

= content_for :script do
  :javascript
    var checkboxes = document.querySelectorAll('input[type=checkbox]')
    for (var i=0; i<checkboxes.length; ++i) {
      var box = checkboxes[i];
      box.addEventListener('change', function(event) {
        var request = jQuery.ajax(event.target.dataset.updateUrl, {
          method: 'PUT',
          data: { checked: event.target.checked + '' }
        });
        //request.done(function() {});
        //request.fail(function(jqXHR, textStatus) {});
      });
    }

app/views/root/index.html.haml
%h1 Chcklst

%h2
  %i.glyphicon.glyphicon-modal-window
  Usage
%p
  %pre
    = "curl -X POST #{Rails.application.secrets.api_base_url}/api/lists.json -d \"title=List title\" -d \"items=item1,item2,item 3\""
%p
  = video_tag "ss.mp4", width: '80%', height: 'auto', controls: true